name: mimo_code
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  switch_button: ^0.0.1
  flutter_advanced_switch: ^3.0.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.7
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/card.jfif
    - assets/images/spotify.jfif
    - assets/images/secCard.jfif
    - assets/images/visaCard.jfif
    - assets/images/spotify-color-svgrepo-com.svg
    - assets/images/amazon-color-svgrepo-com.svg
    - assets/images/apple-color-svgrepo-com.svg
    - assets/images/image.png
    - assets/images/mycard.svg
    - assets/images/apple.svg
    - assets/images/secGoogle.svg
    - assets/images/masterCard.svg
    - assets/images/button.svg
    - assets/images/rec1.svg
    - assets/images/rec2.svg
